### ISSUE TITLE
Garder en mémoire l'emplacement de la liste et la méthode de tri lors d'un retour

### ISSUE THREAD

**Issue by isakbaverel** [StockManagers/StockumGestionum#16]
Après qu'on est consulté une fiche de bouteille, quand on fait un retour arrière on revient au début de la liste et on perd la méthode de tri. Il faudrait trouver un moyen de le garder en mémoire.

**Comment by nalmada** [comment]
commit 8d33e2584209cbcec50b176adad4a73c2c81c36b
Sauvegarde des  options de tri dans les Settings
Le tri sera donc sauvegardé même si on quitte l'application

**Comment by nalmada** [comment]
commit 78caf101e74a155b6840ed25d016b850bc5e3de0

ajout de 
```java 
if (id == android.R.id.home) {
     finish();
}
```

et suppression dans le manifest de 
```xml
            <meta-data
                android:name="android.support.PARENT_ACTIVITY"
                android:value=".StockActivity" />
```
dans les activité concernées pour le retour en arrière sans recréer l'activité.
